### ISSUE TITLE
Can't install latest node-kytea to Ubuntu 16.04 LTS via yarn

### ISSUE THREAD

**Issue by massongit** [hideo55/node-kytea#3]
I tried to install latest node-kytea to Ubuntu 16.04 LTS via yarn 1.7.0.
But yarn displayed this error and installation failed:

```
$ PKG_CONFIG_PATH="/usr/local/lib/pkgconfig" yarn add kytea 
yarn add v1.7.0
[1/4] Resolving packages...
⠂ kytea(node:68838) [DEP0005] DeprecationWarning: Buffer() is deprecated due to security and usability issues. Please use the Buffer.alloc(), Buffer.allocUnsafe(), or Buffer.from() methods instead.
[2/4] Fetching packages...
info fsevents@1.2.4: The platform "linux" is incompatible with this module.
info "fsevents@1.2.4" is an optional dependency and failed compatibility check. Excluding it from installation.
[3/4] Linking dependencies...
warning " > eslint-plugin-jest@21.17.0" has unmet peer dependency "eslint@>=3.6".
[4/4] Building fresh packages...
[1/2] ⠁ uglifyjs-webpack-plugin
error /home/masson/Documents/test_project/node_modules/kytea: Command failed.
Exit code: 1
Command: node-gyp rebuild
Arguments: 
Directory: /home/masson/Documents/test_project/node_modules/kytea
Output:
gyp info it worked if it ends with ok
gyp info using node-gyp@3.6.2
gyp info using node@10.5.0 | linux | x64
gyp info spawn /usr/bin/python2
gyp info spawn args [ '/usr/lib/node_modules/npm/node_modules/node-gyp/gyp/gyp_main.py',
gyp info spawn args   'binding.gyp',
gyp info spawn args   '-f',
gyp info spawn args   'make',
gyp info spawn args   '-I',
gyp info spawn args   '/home/masson/Documents/test_project/node_modules/kytea/build/config.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/usr/lib/node_modules/npm/node_modules/node-gyp/addon.gypi',
gyp info spawn args   '-I',
gyp info spawn args   '/home/masson/.node-gyp/10.5.0/include/node/common.gypi',
gyp info spawn args   '-Dlibrary=shared_library',
gyp info spawn args   '-Dvisibility=default',
gyp info spawn args   '-Dnode_root_dir=/home/masson/.node-gyp/10.5.0',
gyp info spawn args   '-Dnode_gyp_dir=/usr/lib/node_modules/npm/node_modules/node-gyp',
gyp info spawn args   '-Dnode_lib_file=/home/masson/.node-gyp/10.5.0/<(target_arch)/node.lib',
gyp info spawn args   '-Dmodule_root_dir=/home/masson/Documents/test_project/node_modules/kytea',
gyp info spawn args   '-Dnode_engine=v8',
gyp info spawn args   '--depth=.',
gyp info spawn args   '--no-parallel',
gyp info spawn args   '--generator-output',
gyp info spawn args   'build',
gyp info spawn args   '-Goutput_dir=.' ]
gyp info spawn make
gyp info spawn args [ 'BUILDTYPE=Release', '-C', 'build' ]
make: ディレクトリ '/home/masson/Documents/test_project/node_modules/kytea/build'　に入ります
  CXX(target) Release/obj.target/kytea/src/node_kytea.o
In file included from ../../nan/nan.h:184:0,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
../../nan/nan_maybe_43_inl.h: In function ‘Nan::Maybe<bool> Nan::ForceSet(v8::Local<v8::Object>, v8::Local<v8::Value>, v8::Local<v8::Value>, v8::PropertyAttribute)’:
../../nan/nan_maybe_43_inl.h:89:15: error: ‘class v8::Object’ has no member named ‘ForceSet’
   return obj->ForceSet(GetCurrentContext(), key, value, attribs);
               ^
../../nan/nan_maybe_43_inl.h: In function ‘Nan::MaybeLocal<v8::Object> Nan::CloneElementAt(v8::Local<v8::Array>, uint32_t)’:
../../nan/nan_maybe_43_inl.h:221:17: error: ‘class v8::Array’ has no member named ‘CloneElementAt’
   return array->CloneElementAt(GetCurrentContext(), index);
                 ^
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:190,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
../../nan/nan_implementation_12_inl.h: In static member function ‘static Nan::imp::FactoryBase<v8::BooleanObject>::return_t Nan::imp::Factory<v8::BooleanObject>::New(bool)’:
../../nan/nan_implementation_12_inl.h:40:38: error: no matching function for call to ‘v8::BooleanObject::New(bool&)’
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                      ^
In file included from /home/masson/.node-gyp/10.5.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:24,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
/home/masson/.node-gyp/10.5.0/include/node/v8.h:4948:23: note: candidate: static v8::Local<v8::Value> v8::BooleanObject::New(v8::Isolate*, bool)
   static Local<Value> New(Isolate* isolate, bool value);
                       ^
/home/masson/.node-gyp/10.5.0/include/node/v8.h:4948:23: note:   candidate expects 2 arguments, 1 provided
In file included from ../../nan/nan_new.h:189:0,
                 from ../../nan/nan.h:190,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
../../nan/nan_implementation_12_inl.h:40:60: error: expected primary-expression before ‘>’ token
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                                            ^
../../nan/nan_implementation_12_inl.h:40:62: error: expected primary-expression before ‘)’ token
   return v8::BooleanObject::New(value).As<v8::BooleanObject>();
                                                              ^
In file included from ../src/node_kytea.h:7:0,
                 from ../src/node_kytea.cc:1:
../../nan/nan.h: At global scope:
../../nan/nan.h:592:20: error: variable or field ‘AddGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback
                    ^
../../nan/nan.h:592:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback
       ^
../../nan/nan.h:593:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:598:20: error: variable or field ‘RemoveGCEpilogueCallback’ declared void
       v8::Isolate::GCEpilogueCallback callback) {
                    ^
../../nan/nan.h:598:7: error: ‘GCEpilogueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCEpilogueCallback callback) {
       ^
../../nan/nan.h:603:20: error: variable or field ‘AddGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback
                    ^
../../nan/nan.h:603:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback
       ^
../../nan/nan.h:604:18: error: expected primary-expression before ‘gc_type_filter’
     , v8::GCType gc_type_filter = v8::kGCTypeAll) {
                  ^
../../nan/nan.h:609:20: error: variable or field ‘RemoveGCPrologueCallback’ declared void
       v8::Isolate::GCPrologueCallback callback) {
                    ^
../../nan/nan.h:609:7: error: ‘GCPrologueCallback’ is not a member of ‘v8::Isolate’
       v8::Isolate::GCPrologueCallback callback) {
       ^
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:803:60: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, func, argc, argv);
                                                            ^
In file included from ../../nan/nan.h:24:0,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
/home/masson/.node-gyp/10.5.0/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/masson/.node-gyp/10.5.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/node_kytea.h:7:0,
                 from ../src/node_kytea.cc:1:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:817:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::String>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, symbol, argc, argv);
                                                              ^
In file included from ../../nan/nan.h:24:0,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
/home/masson/.node-gyp/10.5.0/include/node/node.h:165:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/masson/.node-gyp/10.5.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/node_kytea.h:7:0,
                 from ../src/node_kytea.cc:1:
../../nan/nan.h: In function ‘v8::Local<v8::Value> Nan::MakeCallback(v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’:
../../nan/nan.h:831:62: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, const char*, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
         v8::Isolate::GetCurrent(), target, method, argc, argv);
                                                              ^
In file included from ../../nan/nan.h:24:0,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
/home/masson/.node-gyp/10.5.0/include/node/node.h:158:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/masson/.node-gyp/10.5.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/node_kytea.h:7:0,
                 from ../src/node_kytea.cc:1:
../../nan/nan.h: In member function ‘v8::Local<v8::Value> Nan::Callback::Call_(v8::Isolate*, v8::Local<v8::Object>, int, v8::Local<v8::Value>*) const’:
../../nan/nan.h:1433:5: warning: ‘v8::Local<v8::Value> node::MakeCallback(v8::Isolate*, v8::Local<v8::Object>, v8::Local<v8::Function>, int, v8::Local<v8::Value>*)’ is deprecated: Use MakeCallback(..., async_context) [-Wdeprecated-declarations]
     ));
     ^
In file included from ../../nan/nan.h:24:0,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
/home/masson/.node-gyp/10.5.0/include/node/node.h:172:50: note: declared here
                 NODE_EXTERN v8::Local<v8::Value> MakeCallback(
                                                  ^
/home/masson/.node-gyp/10.5.0/include/node/node.h:88:42: note: in definition of macro ‘NODE_DEPRECATED’
     __attribute__((deprecated(message))) declarator
                                          ^
In file included from ../src/node_kytea.h:7:0,
                 from ../src/node_kytea.cc:1:
../../nan/nan.h: In function ‘bool Nan::SetAccessor(v8::Local<v8::Object>, v8::Local<v8::String>, Nan::GetterCallback, Nan::SetterCallback, v8::Local<v8::Value>, v8::AccessControl, v8::PropertyAttribute)’:
../../nan/nan.h:1939:16: error: no matching function for call to ‘v8::Object::SetAccessor(v8::Local<v8::String>&, void (*&)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&), void (*&)(v8::Local<v8::Name>, v8::Local<v8::Value>, const v8::PropertyCallbackInfo<void>&), v8::Local<v8::Object>&, v8::AccessControl&, v8::PropertyAttribute&)’
     , attribute);
                ^
In file included from /home/masson/.node-gyp/10.5.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:24,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
/home/masson/.node-gyp/10.5.0/include/node/v8.h:3266:37: note: candidate: v8::Maybe<bool> v8::Object::SetAccessor(v8::Local<v8::Context>, v8::Local<v8::Name>, v8::AccessorNameGetterCallback, v8::AccessorNameSetterCallback, v8::MaybeLocal<v8::Value>, v8::AccessControl, v8::PropertyAttribute, v8::SideEffectType)
   V8_WARN_UNUSED_RESULT Maybe<bool> SetAccessor(
                                     ^
/home/masson/.node-gyp/10.5.0/include/node/v8.h:3266:37: note:   no known conversion for argument 2 from ‘Nan::imp::NativeGetter {aka void (*)(v8::Local<v8::Name>, const v8::PropertyCallbackInfo<v8::Value>&)}’ to ‘v8::Local<v8::Name>’
In file included from ../src/node_kytea.cc:3:0:
../src/node_kytea.cc: In static member function ‘static void node_kytea::NodeKytea::ParseConfig(v8::Handle<v8::Object>, kytea::KyteaConfig*)’:
../src/macros.h:52:51: error: no matching function for call to ‘v8::Value::ToUint32()’
             unsigned int _tmp = _tmpval->ToUint32()->Value(); \
                                                   ^
../src/node_kytea.cc:162:5: note: in expansion of macro ‘CHK_OPT_INT’
     CHK_OPT_INT(config, setTagMax, opt, "tagmax");
     ^
In file included from /home/masson/.node-gyp/10.5.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:24,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
/home/masson/.node-gyp/10.5.0/include/node/v8.h:2406:44: note: candidate: v8::MaybeLocal<v8::Uint32> v8::Value::ToUint32(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
                                            ^
/home/masson/.node-gyp/10.5.0/include/node/v8.h:2406:44: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node_kytea.cc:3:0:
../src/macros.h:41:74: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
             std::string _tmp = *v8::String::Utf8Value(_tmpval->ToString()); \
                                                                          ^
../src/node_kytea.cc:163:5: note: in expansion of macro ‘CHK_OPT_STR’
     CHK_OPT_STR(config, setDefaultTag, opt, "deftag");
     ^
In file included from /home/masson/.node-gyp/10.5.0/include/node/v8.h:26:0,
                 from /home/masson/.node-gyp/10.5.0/include/node/node.h:63,
                 from ../../nan/nan.h:24,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
/home/masson/.node-gyp/10.5.0/include/node/v8.h:2852:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/masson/.node-gyp/10.5.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
In file included from ../src/node_kytea.cc:3:0:
../src/macros.h:52:51: error: no matching function for call to ‘v8::Value::ToUint32()’
             unsigned int _tmp = _tmpval->ToUint32()->Value(); \
                                                   ^
../src/node_kytea.cc:165:5: note: in expansion of macro ‘CHK_OPT_INT’
     CHK_OPT_INT(config, setUnkBeam, opt, "unkbeam");
     ^
In file included from /home/masson/.node-gyp/10.5.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:24,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
/home/masson/.node-gyp/10.5.0/include/node/v8.h:2406:44: note: candidate: v8::MaybeLocal<v8::Uint32> v8::Value::ToUint32(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
                                            ^
/home/masson/.node-gyp/10.5.0/include/node/v8.h:2406:44: note:   candidate expects 1 argument, 0 provided
In file included from ../src/node_kytea.cc:3:0:
../src/macros.h:41:74: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
             std::string _tmp = *v8::String::Utf8Value(_tmpval->ToString()); \
                                                                          ^
../src/node_kytea.cc:166:5: note: in expansion of macro ‘CHK_OPT_STR’
     CHK_OPT_STR(config, setUnkTag, opt, "unktag");
     ^
In file included from /home/masson/.node-gyp/10.5.0/include/node/v8.h:26:0,
                 from /home/masson/.node-gyp/10.5.0/include/node/node.h:63,
                 from ../../nan/nan.h:24,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
/home/masson/.node-gyp/10.5.0/include/node/v8.h:2852:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/masson/.node-gyp/10.5.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/node_kytea.cc:175:89: error: no matching function for call to ‘v8::Value::ToUint32()’
                     unsigned int tag_index = notag->Get(Nan::New<Integer>(i))->ToUint32()->Value();
                                                                                         ^
In file included from /home/masson/.node-gyp/10.5.0/include/node/node.h:63:0,
                 from ../../nan/nan.h:24,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
/home/masson/.node-gyp/10.5.0/include/node/v8.h:2406:44: note: candidate: v8::MaybeLocal<v8::Uint32> v8::Value::ToUint32(v8::Local<v8::Context>) const
   V8_WARN_UNUSED_RESULT MaybeLocal<Uint32> ToUint32(
                                            ^
/home/masson/.node-gyp/10.5.0/include/node/v8.h:2406:44: note:   candidate expects 1 argument, 0 provided
../src/node_kytea.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE node_kytea::NodeKytea::Open(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/node_kytea.cc:195:66: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     std::string filename = *String::Utf8Value(info[0]->ToString());
                                                                  ^
In file included from /home/masson/.node-gyp/10.5.0/include/node/v8.h:26:0,
                 from /home/masson/.node-gyp/10.5.0/include/node/node.h:63,
                 from ../../nan/nan.h:24,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
/home/masson/.node-gyp/10.5.0/include/node/v8.h:2852:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/masson/.node-gyp/10.5.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/node_kytea.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE node_kytea::NodeKytea::getWS(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/node_kytea.cc:209:66: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     std::string sentence = *String::Utf8Value(info[0]->ToString());
                                                                  ^
In file included from /home/masson/.node-gyp/10.5.0/include/node/v8.h:26:0,
                 from /home/masson/.node-gyp/10.5.0/include/node/node.h:63,
                 from ../../nan/nan.h:24,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
/home/masson/.node-gyp/10.5.0/include/node/v8.h:2852:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/masson/.node-gyp/10.5.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/node_kytea.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE node_kytea::NodeKytea::getTags(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/node_kytea.cc:224:66: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     std::string sentence = *String::Utf8Value(info[0]->ToString());
                                                                  ^
In file included from /home/masson/.node-gyp/10.5.0/include/node/v8.h:26:0,
                 from /home/masson/.node-gyp/10.5.0/include/node/node.h:63,
                 from ../../nan/nan.h:24,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
/home/masson/.node-gyp/10.5.0/include/node/v8.h:2852:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/masson/.node-gyp/10.5.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
../src/node_kytea.cc: In static member function ‘static Nan::NAN_METHOD_RETURN_TYPE node_kytea::NodeKytea::getAllTags(Nan::NAN_METHOD_ARGS_TYPE)’:
../src/node_kytea.cc:239:66: warning: ‘v8::String::Utf8Value::Utf8Value(v8::Local<v8::Value>)’ is deprecated: Use Isolate version [-Wdeprecated-declarations]
     std::string sentence = *String::Utf8Value(info[0]->ToString());
                                                                  ^
In file included from /home/masson/.node-gyp/10.5.0/include/node/v8.h:26:0,
                 from /home/masson/.node-gyp/10.5.0/include/node/node.h:63,
                 from ../../nan/nan.h:24,
                 from ../src/node_kytea.h:7,
                 from ../src/node_kytea.cc:1:
/home/masson/.node-gyp/10.5.0/include/node/v8.h:2852:28: note: declared here
                   explicit Utf8Value(Local<v8::Value> obj));
                            ^
/home/masson/.node-gyp/10.5.0/include/node/v8config.h:324:3: note: in definition of macro ‘V8_DEPRECATED’
   declarator __attribute__((deprecated(message)))
   ^
kytea.target.mk:100: ターゲット 'Release/obj.target/kytea/src/node_kytea.o' のレシピで失敗しました
make: ディレクトリ '/home/masson/Documents/test_project/node_modules/kytea/build' から出ます
make: *** [Release/obj.target/kytea/src/node_kytea.o] エラー 1
gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:258:23)
gyp ERR! stack     at ChildProcess.emit (events.js:182:13)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
gyp ERR! System Linux 4.4.0-127-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/masson/Documents/test_project/node_modules/kytea
gyp ERR! node -v v10.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
```

I use node 10.5.0 and KyTea 0.4.7. Also, `kytea.pc` is in `/usr/local/lib/pkgconfig/`.

**Comment by massongit** [comment]
I downgraded the node to 8.11.3 and upgraded the version of the dependent package nan to 2.10.0 (See #4) and successfully installed this module.

**Comment by massongit** [comment]
I updated the version of nan so that I can install this module on node 9.9.0.
